### ISSUE TITLE
RTYAML not recognizing `\r\n` as line ending to format text block

### ISSUE THREAD

**Issue by gregelin** [unitedstates/rtyaml#3]
RTYAML appears to not be reformatting blocks of text containing `\r\n` instead of `\n`.

I am looking RTYAML source, and don’t want to change without checking.  Also wondering what happens if `\n` is include in text box, but escaped (`\\n`) when quoted, or can that not happen?

**Comment by gregelin** [comment]
@JoshData Here is an example of YAML data that RTYAML did not format as an improved formatted test block because the text contained `\r\n`:

```
questions:
- id: system_short_name
  title: System Short Name
  prompt: "What is the system's nickname or abbreviation?\r\n\r\nGreat! The full name
    of IT System is \"**{{system_name}}**.\" What about a short name,  acronym or
    nickname  for your IT System?"
  type: text
- id: system_description
  title: System Description
  prompt: "General system description.\r\n\r\nDescribe what system does and its general
    purpose to your organization. (This is your main description of {% if system_short_name
    %} {{system_short_name}}{% else %}your IT System {% endif %}. We'll get a more
    technical description later.)"
  type: longtext
```

Maybe the issue is how underling C library is handling the code?

**Comment by JoshData** [comment]
At https://github.com/unitedstates/rtyaml/blob/master/rtyaml/__init__.py#L68, we give pyyaml a hint about what type of string output format to use (folded block, literal block, quoted string, etc.). It only checks if \n is in the string but could also check if \r is in the string.

**Comment by JoshData** [comment]
Er.... But since Windows newlines have both \r and \n, that line should be working anyway --- nevermind my last comment.

**Comment by JoshData** [comment]
I played around with pyyaml a bit just now and I believe that pyyaml simply requires strings to have Unix line ending (`\n` only) in order to use the nice unquoted block style. The rationale is probably that when a string is written in block style in the YAML output, the newlines _within the string value_ must match the newlines used in the rest of the YAML document, i.e.

```
key1: value1 [NEWLINE]
key2: value2 [NEWLINE]
key3: | [NEWLINE]
   Some text here. [NEWLINE]
   Second line of text here.  [NEWLINE]
...
```

It wouldn't make sense if the newlines above and below the key3 string value were Unix style but the newlines in the middle of key3's value were Windows-style.

pyyaml has an option to control whether the entire output is done with Unix or Windows line endings (`yaml.dump(value, line_break="\r\n")`), but this doesn't help fix the problem you're having --- it still expects string values to have Unix line endings only (if you want block style strings).

So I believe the solution is to sanitize all inputs to ensure there are only `\n`s, i.e. `s.replace("\r\n", "\n")`.

**Comment by GPHemsley** [comment]
The [Python documentation for the built-in csv library](https://docs.python.org/3/library/csv.html) recommends using `newline=""` with `open()` to deal with similar issues. Is it possible that that suggestion would help here too? (I notice the README for rtyaml is not suggesting doing that.)

**Comment by JoshData** [comment]
The choice about whether to use a quoted or block style for the value is made before it goes to a file, so it won't help on output (although it could be relevant if the string value is coming from a file originally --- but setting `open()`'s `newline` is likely to cause problems).

**Comment by gregelin** [comment]
So the recommendation is to address issue by convert \r\n to \n before initial save of content?

**Comment by JoshData** [comment]
Right. Closing the issue. :)
